#!/usr/bin/env python3
from __future__ import annotations

import argparse
import os
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any


class AcceptanceEnvError(RuntimeError):
    pass


DEFAULT_DATA_ROOT = "/srv/b1-ai-hub"
DEFAULT_HOSTS = {
    "api": "api.ai.b1.germering",
    "comfy": "comfy.ai.b1.germering",
    "voice": "voice.ai.b1.germering",
    "models": "models.ai.b1.germering",
    "legacy_comfy": "ai.b1.germering:8188",
}
LIVE_FLAGS = {
    "B1_SMOKE_LIVE_TEST": "1",
    "B1_WORKFLOWS_LIVE_TEST": "1",
    "B1_LOCALAI_ACCEPTANCE_LIVE_TEST": "1",
    "B1_GPU_ACCEPTANCE_LIVE_TEST": "1",
    "B1_NATIVE_COMFYUI_LIVE_TEST": "1",
    "B1_REMOTE_NODES_LIVE_TEST": "1",
    "B1_MODELHUB_LIVE_TEST": "1",
    "B1_VOICEBOX_LIVE_TEST": "1",
    "B1_SECURITY_LIVE_TEST": "1",
    "B1_RESTART_RECONCILIATION_LIVE_TEST": "1",
}
EVIDENCE_FILES = {
    "B1_PREFLIGHT_EVIDENCE": "operator-preflight.json",
    "B1_SMOKE_EVIDENCE": "live-smoke.json",
    "B1_WORKFLOWS_EVIDENCE": "installed-workflows.json",
    "B1_LOCALAI_ACCEPTANCE_EVIDENCE": "localai-runtime.json",
    "B1_GPU_ACCEPTANCE_EVIDENCE": "cross-runtime-gpu.json",
    "B1_NATIVE_COMFYUI_EVIDENCE": "native-comfyui.json",
    "B1_LEGACY_COMFY_EVIDENCE": "legacy-comfy-listener.json",
    "B1_REMOTE_NODES_EVIDENCE": "remote-nodes-non-comfy.json",
    "B1_MODELHUB_EVIDENCE": "modelhub-client-sync.json",
    "B1_VOICEBOX_EVIDENCE": "voicebox-remote.json",
    "B1_SECURITY_EVIDENCE": "security-acceptance.json",
    "B1_RESTART_RECONCILIATION_EVIDENCE": "restart-reconciliation.json",
}


@dataclass(frozen=True)
class AcceptanceEnvConfig:
    data_root: Path = Path(DEFAULT_DATA_ROOT)
    output: Path | None = None
    host_api: str = DEFAULT_HOSTS["api"]
    host_comfy: str = DEFAULT_HOSTS["comfy"]
    host_voice: str = DEFAULT_HOSTS["voice"]
    host_models: str = DEFAULT_HOSTS["models"]
    legacy_comfy_host: str = DEFAULT_HOSTS["legacy_comfy"]
    force: bool = False


def default_output_path(data_root: Path) -> Path:
    backup_root = Path(os.getenv("B1_BACKUP_ROOT", str(data_root / "backups")))
    return backup_root / "acceptance" / "operator-live-acceptance.env"


def shell_default_literal(key: str, value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$").replace("`", "\\`")
    return f'export {key}="${{{key}:-{escaped}}}"'


def shell_assign_literal(key: str, value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$").replace("`", "\\`")
    return f'export {key}="{escaped}"'


def shell_default_expression(key: str, expression: str) -> str:
    return f'export {key}="${{{key}:-{expression}}}"'


def section(title: str) -> list[str]:
    return ["", f"# {title}"]


def render_acceptance_env(config: AcceptanceEnvConfig) -> str:
    data_root = config.data_root
    backup_root = data_root / "backups"
    acceptance_root = backup_root / "acceptance"
    workflows_root = data_root / "workflows" / "acceptance"
    ca_file = data_root / "data" / "caddy" / "pki" / "authorities" / "local" / "root.crt"
    api_base = f"https://{config.host_api}"
    comfy_base = f"https://{config.host_comfy}"
    voice_base = f"https://{config.host_voice}"
    models_base = f"https://{config.host_models}"
    legacy_comfy_base = f"http://{config.legacy_comfy_host}"

    lines: list[str] = [
        "# B1 AI Hub operator live-acceptance environment.",
        "# Generated by deploy/scripts/acceptance_env.py.",
        "# Review this file before sourcing it. It intentionally contains no API keys, browser passwords, cookies, or model-download tokens.",
        "# Set B1_ACCEPTANCE_API_KEY before sourcing, or edit the blank key lines below with scoped operator/admin keys.",
        "# The restart reconciliation timestamp and Model Hub sync aliases must be filled for final handoff evidence.",
    ]
    lines.extend(section("Shared paths and transport policy"))
    lines.append(shell_default_literal("B1_DATA_ROOT", str(data_root)))
    lines.append(shell_default_literal("B1_BACKUP_ROOT", str(backup_root)))
    lines.append(shell_default_literal("B1_ACCEPTANCE_CA_FILE", str(ca_file)))
    lines.append(shell_default_literal("B1_ACCEPTANCE_API_BASE", api_base))
    lines.append(shell_default_expression("B1_ACCEPTANCE_API_KEY", ""))

    lines.extend(section("Handoff safety gates"))
    lines.append(shell_assign_literal("B1_ACCEPTANCE_ALLOW_INSECURE_HTTP", "false"))
    lines.append(shell_assign_literal("B1_MODEL_CLIENT_ALLOW_INSECURE_HTTP", "false"))
    lines.append(shell_assign_literal("B1_AI_HUB_ALLOW_INSECURE_HTTP", "false"))
    lines.append(shell_assign_literal("B1_SMOKE_ALLOW_PLACEHOLDER", "false"))
    lines.append(shell_assign_literal("B1_WORKFLOWS_ALLOW_PLACEHOLDER", "false"))
    lines.append(shell_assign_literal("B1_REMOTE_NODES_ALLOW_PLACEHOLDER", "false"))
    lines.append(shell_assign_literal("B1_GPU_ACCEPTANCE_ALLOW_RECOVERY_DRY_RUN", "false"))
    lines.append(shell_assign_literal("B1_GPU_ACCEPTANCE_SKIP_VOICEBOX", "false"))
    lines.append(shell_assign_literal("B1_LOCALAI_ACCEPTANCE_REQUIRE_PRODUCTION", "true"))
    lines.append(shell_assign_literal("B1_GPU_ACCEPTANCE_REQUIRE_PRODUCTION", "true"))
    lines.append(shell_assign_literal("B1_GPU_ACCEPTANCE_ENFORCE_VRAM_RESERVE", "true"))
    lines.append(shell_assign_literal("B1_MODELHUB_ACCEPT_LICENSES", "0"))

    lines.extend(section("Common API keys"))
    for key in (
        "B1_AI_HUB_API_KEY",
        "B1_SMOKE_API_KEY",
        "B1_SMOKE_ADMIN_API_KEY",
        "B1_WORKFLOWS_API_KEY",
        "B1_LOCALAI_ACCEPTANCE_API_KEY",
        "B1_GPU_ACCEPTANCE_API_KEY",
        "B1_RESTART_RECONCILIATION_API_KEY",
        "B1_NATIVE_COMFYUI_API_KEY",
        "B1_REMOTE_NODES_API_KEY",
        "B1_SECURITY_API_KEY",
        "B1_VOICEBOX_API_KEY",
        "B1_VOICEBOX_NATIVE_API_KEY",
        "B1_MODELHUB_TOKEN",
    ):
        lines.append(shell_default_expression(key, "$B1_ACCEPTANCE_API_KEY"))

    lines.extend(section("Live harness enable flags"))
    for key, value in LIVE_FLAGS.items():
        lines.append(shell_default_literal(key, value))
    lines.append(shell_default_literal("B1_GPU_ACCEPTANCE_RUN_RECOVERY_ACTION", "1"))
    lines.append(shell_default_literal("B1_SECURITY_CREATE_TEMP_UNDERSCOPED_CLIENT", "1"))
    lines.append(shell_default_literal("B1_REMOTE_NODES_COMFYUI_STOP_MODE", "manual"))

    lines.extend(section("Base URLs"))
    for key in (
        "B1_AI_HUB_API_BASE",
        "B1_SMOKE_API_BASE",
        "B1_WORKFLOWS_API_BASE",
        "B1_LOCALAI_ACCEPTANCE_API_BASE",
        "B1_GPU_ACCEPTANCE_API_BASE",
        "B1_RESTART_RECONCILIATION_API_BASE",
        "B1_NATIVE_COMFYUI_API_BASE",
        "B1_SECURITY_API_BASE",
        "B1_VOICEBOX_API_BASE",
    ):
        lines.append(shell_default_expression(key, "$B1_ACCEPTANCE_API_BASE"))
    lines.append(shell_default_literal("B1_NATIVE_COMFYUI_BASE", comfy_base))
    lines.append(shell_default_literal("B1_SECURITY_COMFY_BASE", comfy_base))
    lines.append(shell_default_literal("B1_VOICEBOX_BASE", voice_base))
    lines.append(shell_default_literal("B1_MODELHUB_URL", models_base))
    lines.append(shell_default_literal("B1_LEGACY_COMFY_BASE", legacy_comfy_base))

    lines.extend(section("TLS CA and verification"))
    for key in (
        "B1_SMOKE_CA_FILE",
        "B1_WORKFLOWS_CA_FILE",
        "B1_LOCALAI_ACCEPTANCE_CA_FILE",
        "B1_GPU_ACCEPTANCE_CA_FILE",
        "B1_RESTART_RECONCILIATION_CA_FILE",
        "B1_NATIVE_COMFYUI_CA_FILE",
        "B1_SECURITY_CA_FILE",
        "B1_VOICEBOX_CA_FILE",
        "B1_MODELHUB_CA_FILE",
        "B1_AI_HUB_CA_FILE",
    ):
        lines.append(shell_default_expression(key, "$B1_ACCEPTANCE_CA_FILE"))
    for key in (
        "B1_SMOKE_TLS_VERIFY",
        "B1_WORKFLOWS_TLS_VERIFY",
        "B1_LOCALAI_ACCEPTANCE_TLS_VERIFY",
        "B1_GPU_ACCEPTANCE_TLS_VERIFY",
        "B1_RESTART_RECONCILIATION_TLS_VERIFY",
        "B1_NATIVE_COMFYUI_TLS_VERIFY",
        "B1_SECURITY_TLS_VERIFY",
        "B1_VOICEBOX_TLS_VERIFY",
        "B1_LEGACY_COMFY_TLS_VERIFY",
    ):
        lines.append(shell_default_literal(key, "1"))

    lines.extend(section("Evidence output files"))
    for key, filename in EVIDENCE_FILES.items():
        lines.append(shell_default_literal(key, str(acceptance_root / filename)))

    lines.extend(section("Prompt, job, and artifact inputs"))
    lines.append(shell_default_literal("B1_GPU_ACCEPTANCE_COMFY_PROMPT_FILE", str(workflows_root / "text-to-image-api-prompt.json")))
    lines.append(shell_default_literal("B1_NATIVE_COMFYUI_PROMPT_FILE", str(workflows_root / "text-to-image-api-prompt.json")))
    lines.append(shell_default_literal("B1_WORKFLOWS_IMAGE_JOB_FILE", str(workflows_root / "image-generation-job.json")))
    lines.append(shell_default_literal("B1_WORKFLOWS_IMAGE_EDIT_JOB_FILE", str(workflows_root / "image-edit-job.json")))
    lines.append(shell_default_literal("B1_WORKFLOWS_VIDEO_JOB_FILE", str(workflows_root / "short-video-job.json")))
    lines.append(shell_default_literal("B1_AI_HUB_DOWNLOAD_DIR", str(data_root / "artifacts" / "temporary" / "remote-node-acceptance")))

    lines.extend(section("Operator-supplied final handoff values"))
    lines.append(shell_default_expression("B1_RESTART_RECONCILIATION_STARTED_AFTER", ""))
    lines.append(shell_default_expression("B1_MODELHUB_SYNC_MODEL", ""))
    lines.append(shell_default_expression("B1_MODELHUB_INFERENCE_ONLY_MODEL", ""))
    lines.append(shell_default_expression("B1_SECURITY_BROWSER_USERNAME", ""))
    lines.append(shell_default_expression("B1_SECURITY_BROWSER_PASSWORD", ""))
    lines.append(shell_default_expression("B1_SECURITY_BROWSER_SESSION_COOKIE", ""))
    lines.append(shell_default_expression("B1_SECURITY_UNDERSCOPED_API_KEY", ""))
    lines.append(shell_default_expression("B1_SECURITY_ARTIFACT_READER_API_KEY", ""))
    lines.append(shell_default_expression("B1_SECURITY_ARTIFACT_JOB_ID", ""))
    lines.append(shell_default_expression("B1_SECURITY_ARTIFACT_URL", ""))
    lines.append(shell_default_expression("B1_VOICEBOX_SPEECH_LIMITATION", ""))
    lines.append(shell_default_expression("B1_VOICEBOX_WEBSOCKET_LIMITATION", ""))

    lines.extend(section("Runbook reminder"))
    lines.append("# 1. export B1_ACCEPTANCE_API_KEY=... or edit the key lines above.")
    lines.append("# 2. Fill B1_RESTART_RECONCILIATION_STARTED_AFTER after preparing and restarting the drill state.")
    lines.append("# 3. Fill B1_MODELHUB_SYNC_MODEL and B1_MODELHUB_INFERENCE_ONLY_MODEL after reviewing Model Hub permissions.")
    lines.append("# 4. Source this file, then run: make acceptance-preflight")
    lines.append("# 5. When preflight passes, run: make operator-live-acceptance")
    return "\n".join(lines) + "\n"


def assert_writable_target(path: Path, *, force: bool) -> None:
    if path.exists():
        if path.is_symlink():
            raise AcceptanceEnvError(f"refusing to write through symlink: {path}")
        if not path.is_file():
            raise AcceptanceEnvError(f"refusing to overwrite non-regular file: {path}")
        if not force:
            raise AcceptanceEnvError(f"{path} already exists; rerun with --force after preserving operator edits")
    current = path.parent
    while current != current.parent:
        if current.exists() and current.is_symlink():
            raise AcceptanceEnvError(f"refusing to write inside symlinked directory: {current}")
        current = current.parent


def write_private_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(prefix=f".{path.name}.", suffix=".tmp", dir=path.parent)
    tmp_path = Path(tmp_name)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        tmp_path.chmod(0o640)
        os.replace(tmp_path, path)
        path.chmod(0o640)
    finally:
        if tmp_path.exists():
            tmp_path.unlink()


def generate_acceptance_env(config: AcceptanceEnvConfig) -> dict[str, Any]:
    output = config.output or default_output_path(config.data_root)
    output = output if output.is_absolute() else Path.cwd() / output
    existed = output.exists()
    assert_writable_target(output, force=config.force)
    content = render_acceptance_env(config)
    write_private_text(output, content)
    return {
        "output": str(output),
        "data_root": str(config.data_root),
        "created": not existed,
        "bytes": len(content.encode("utf-8")),
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate a sourceable B1 AI Hub live-acceptance environment file.")
    parser.add_argument("--data-root", "--root", dest="data_root", default=os.getenv("B1_DATA_ROOT", DEFAULT_DATA_ROOT))
    parser.add_argument("--output", default="", help="File to create. Defaults to $B1_BACKUP_ROOT/acceptance/operator-live-acceptance.env.")
    parser.add_argument("--host-api", default=os.getenv("B1_HOST_API", DEFAULT_HOSTS["api"]))
    parser.add_argument("--host-comfy", default=os.getenv("B1_HOST_COMFY", DEFAULT_HOSTS["comfy"]))
    parser.add_argument("--host-voice", default=os.getenv("B1_HOST_VOICE", DEFAULT_HOSTS["voice"]))
    parser.add_argument("--host-models", default=os.getenv("B1_HOST_MODELS", DEFAULT_HOSTS["models"]))
    parser.add_argument("--legacy-comfy-host", default=os.getenv("B1_LEGACY_COMFY_HOST", DEFAULT_HOSTS["legacy_comfy"]))
    parser.add_argument("--force", action="store_true", help="Overwrite an existing generated file after preserving operator edits.")
    parser.add_argument("--print", action="store_true", dest="print_only", help="Print to stdout instead of writing a file.")
    return parser.parse_args()


def config_from_args(args: argparse.Namespace) -> AcceptanceEnvConfig:
    data_root = Path(str(args.data_root)).expanduser()
    output = Path(str(args.output)).expanduser() if str(args.output).strip() else None
    return AcceptanceEnvConfig(
        data_root=data_root,
        output=output,
        host_api=str(args.host_api).strip() or DEFAULT_HOSTS["api"],
        host_comfy=str(args.host_comfy).strip() or DEFAULT_HOSTS["comfy"],
        host_voice=str(args.host_voice).strip() or DEFAULT_HOSTS["voice"],
        host_models=str(args.host_models).strip() or DEFAULT_HOSTS["models"],
        legacy_comfy_host=str(args.legacy_comfy_host).strip() or DEFAULT_HOSTS["legacy_comfy"],
        force=bool(args.force),
    )


def main() -> None:
    args = parse_args()
    config = config_from_args(args)
    if args.print_only:
        print(render_acceptance_env(config), end="")
        return
    result = generate_acceptance_env(config)
    print(f"created {result['output']}")
    print("review it, set the blank operator-supplied values, then source it before running make operator-live-acceptance")


if __name__ == "__main__":
    main()
