#!/usr/bin/env python3
from __future__ import annotations

import argparse
import difflib
import json
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_SCHEMA = ROOT / "docs" / "openapi.json"
DEFAULT_OUTPUTS = (
    ROOT / "web" / "control-center" / "src" / "generated" / "b1-api-client.ts",
    ROOT / "web" / "media-studio" / "src" / "generated" / "b1-api-client.ts",
)
SAFE_METHODS = {"GET", "HEAD", "OPTIONS", "TRACE"}


def ts_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def load_schema(path: Path) -> dict[str, Any]:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise RuntimeError(f"cannot read OpenAPI schema: {path}") from exc
    if not isinstance(payload, dict) or not str(payload.get("openapi", "")).startswith("3.1."):
        raise RuntimeError(f"{path} is not an OpenAPI 3.1 schema")
    paths = payload.get("paths")
    if not isinstance(paths, dict) or not paths:
        raise RuntimeError(f"{path} does not contain any paths")
    return payload


def route_rows(schema: dict[str, Any]) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    for path, operations in sorted(schema["paths"].items()):
        if not isinstance(path, str) or not isinstance(operations, dict):
            continue
        for method, operation in sorted(operations.items()):
            upper = method.upper()
            if upper not in {"GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"}:
                continue
            operation_id = ""
            if isinstance(operation, dict) and isinstance(operation.get("operationId"), str):
                operation_id = operation["operationId"]
            rows.append({"key": f"{upper} {path}", "method": upper, "path": path, "operation_id": operation_id})
    if not rows:
        raise RuntimeError("OpenAPI schema did not expose any HTTP routes")
    return rows


def render_client(schema: dict[str, Any]) -> str:
    rows = route_rows(schema)
    route_entries = []
    seen_paths: set[str] = set()
    path_entries = []
    for row in rows:
        route_entries.append(
            f"  {ts_string(row['key'])}: {{ method: {ts_string(row['method'])}, path: {ts_string(row['path'])}, operationId: {ts_string(row['operation_id'])} }},"
        )
        if row["path"] not in seen_paths:
            seen_paths.add(row["path"])
            path_entries.append(f"  {ts_string(row['path'])},")
    safe_methods = ", ".join(ts_string(method) for method in sorted(SAFE_METHODS))
    return "\n".join(
        [
            "/*",
            " * Generated by deploy/scripts/generate_openapi_client.py from docs/openapi.json.",
            " * Do not edit by hand.",
            " */",
            "",
            "export type B1HttpMethod = \"GET\" | \"POST\" | \"PUT\" | \"PATCH\" | \"DELETE\" | \"HEAD\" | \"OPTIONS\" | \"TRACE\";",
            "",
            "export const B1_API_ROUTES = {",
            *route_entries,
            "} as const;",
            "",
            "export const B1_API_PATHS = [",
            *path_entries,
            "] as const;",
            "",
            "export type B1ApiRouteKey = keyof typeof B1_API_ROUTES;",
            "export type B1ApiPath = typeof B1_API_PATHS[number];",
            "export type B1ApiRequestPath = B1ApiPath | `/${string}` | `http://${string}` | `https://${string}`;",
            "",
            "export type B1ApiClientOptions = {",
            "  baseUrl: string;",
            "  credentials?: RequestCredentials;",
            "  getBearerToken?: () => string;",
            "  getCsrfToken?: () => string | null;",
            "};",
            "",
            f"const SAFE_METHODS = new Set<B1HttpMethod>([{safe_methods}]);",
            "",
            "function normalizedBaseUrl(value: string): string {",
            "  return value.replace(/\\/+$/, \"\");",
            "}",
            "",
            "function requestUrl(baseUrl: string, path: B1ApiRequestPath): string {",
            "  const value = String(path);",
            "  return value.startsWith(\"http://\") || value.startsWith(\"https://\") ? value : `${baseUrl}${value}`;",
            "}",
            "",
            "function responseErrorDetail(parsed: unknown, response: Response): string {",
            "  const detail = typeof parsed === \"object\" && parsed !== null && \"detail\" in parsed ? (parsed as { detail?: unknown }).detail : undefined;",
            "  if (typeof detail === \"string\") return detail;",
            "  if (typeof detail === \"object\" && detail !== null && \"message\" in detail) {",
            "    const message = (detail as { message?: unknown }).message;",
            "    if (typeof message === \"string\") return message;",
            "  }",
            "  if (Array.isArray(detail)) {",
            "    return detail.map((item) => {",
            "      if (typeof item === \"object\" && item !== null) {",
            "        const record = item as { msg?: unknown; message?: unknown };",
            "        return String(record.msg ?? record.message ?? item);",
            "      }",
            "      return String(item);",
            "    }).join(\"; \");",
            "  }",
            "  return `${response.status} ${response.statusText}`;",
            "}",
            "",
            "export class B1ApiClient {",
            "  private readonly baseUrl: string;",
            "  private readonly credentials: RequestCredentials;",
            "  private readonly getBearerToken?: () => string;",
            "  private readonly getCsrfToken?: () => string | null;",
            "",
            "  constructor(options: B1ApiClientOptions) {",
            "    this.baseUrl = normalizedBaseUrl(options.baseUrl);",
            "    this.credentials = options.credentials ?? \"include\";",
            "    this.getBearerToken = options.getBearerToken;",
            "    this.getCsrfToken = options.getCsrfToken;",
            "  }",
            "",
            "  url(path: B1ApiRequestPath): string {",
            "    return requestUrl(this.baseUrl, path);",
            "  }",
            "",
            "  requestHeaders(method: string, initial?: HeadersInit): Headers {",
            "    const headers = new Headers(initial);",
            "    const normalizedMethod = method.toUpperCase() as B1HttpMethod;",
            "    const token = this.getBearerToken?.().trim();",
            "    if (token) {",
            "      headers.set(\"Authorization\", `Bearer ${token}`);",
            "      return headers;",
            "    }",
            "    if (!SAFE_METHODS.has(normalizedMethod) && !headers.has(\"X-B1-CSRF\")) {",
            "      const csrf = this.getCsrfToken?.();",
            "      if (csrf) headers.set(\"X-B1-CSRF\", csrf);",
            "    }",
            "    return headers;",
            "  }",
            "",
            "  fetch(path: B1ApiRequestPath, init: RequestInit = {}): Promise<Response> {",
            "    const method = (init.method ?? \"GET\").toUpperCase();",
            "    const headers = this.requestHeaders(method, init.headers);",
            "    return globalThis.fetch(this.url(path), { ...init, credentials: this.credentials, headers });",
            "  }",
            "",
            "  async json<T>(path: B1ApiRequestPath, init: RequestInit = {}): Promise<T> {",
            "    const headers = new Headers(init.headers);",
            "    if (init.body !== undefined && !headers.has(\"Content-Type\")) headers.set(\"Content-Type\", \"application/json\");",
            "    const response = await this.fetch(path, { ...init, headers });",
            "    const body = await response.text();",
            "    const parsed = body ? JSON.parse(body) : null;",
            "    if (!response.ok) throw new Error(responseErrorDetail(parsed, response));",
            "    return parsed as T;",
            "  }",
            "}",
            "",
        ]
    )


def check_file(path: Path, expected: str) -> int:
    if not path.exists():
        print(f"{path} does not exist; run: python3 deploy/scripts/generate_openapi_client.py", file=sys.stderr)
        return 1
    current = path.read_text(encoding="utf-8")
    if current == expected:
        print(f"{path} is up to date")
        return 0
    diff = difflib.unified_diff(
        current.splitlines(keepends=True),
        expected.splitlines(keepends=True),
        fromfile=str(path),
        tofile=f"{path} (generated)",
    )
    sys.stderr.writelines(diff)
    return 1


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate or validate the B1 AI Hub TypeScript OpenAPI client.")
    parser.add_argument("--schema", type=Path, default=DEFAULT_SCHEMA, help="OpenAPI schema path. Defaults to docs/openapi.json.")
    parser.add_argument("--output", action="append", type=Path, help="Client output path. May be supplied more than once.")
    parser.add_argument("--check", action="store_true", help="Fail when generated output differs from committed files.")
    args = parser.parse_args()

    schema = load_schema(args.schema.resolve())
    expected = render_client(schema)
    outputs = tuple(path.resolve() for path in (args.output or DEFAULT_OUTPUTS))
    if args.check:
        return max(check_file(path, expected) for path in outputs)
    for output in outputs:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(expected, encoding="utf-8")
        print(f"wrote {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
