from __future__ import annotations

import hashlib
import json
import re
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from . import update_policy


UPDATE_ID_RE = re.compile(r"^update_[A-Za-z0-9]{8,64}$")
PROMOTABLE_IMAGE_STAGE_STATUSES = {"ok", "already_present", "pulled"}


class ComposeOverrideError(ValueError):
    pass


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def validate_update_id(update_id: str) -> str:
    if not UPDATE_ID_RE.fullmatch(update_id):
        raise ComposeOverrideError(f"invalid update id: {update_id}")
    return update_id


def normalize_image_refs(image_refs: list[dict[str, Any]]) -> list[dict[str, str]]:
    try:
        return update_policy.normalize_image_refs(image_refs)
    except update_policy.UpdatePolicyError as exc:
        raise ComposeOverrideError(str(exc)) from exc


def render_compose_image_override(
    *,
    update_id: str,
    target_version: str,
    image_refs: list[dict[str, Any]],
    created_at: datetime | None = None,
) -> str:
    normalized_refs = normalize_image_refs(image_refs)
    timestamp = (created_at or datetime.now(tz=UTC)).astimezone(UTC).isoformat()
    lines = [
        "# Generated by B1 AI Hub controlled-update staging.",
        f"# Update: {validate_update_id(update_id)}",
        f"# Target version: {target_version}",
        f"# Created at: {timestamp}",
        "# Use only during a maintenance window after backups and image staging have succeeded.",
        "services:",
    ]
    for item in normalized_refs:
        lines.extend(
            [
                f"  {item['service']}:",
                f"    image: {json.dumps(item['image'])}",
                "    build: null",
            ]
        )
    return "\n".join(lines) + "\n"


def stage_statuses(image_stage: list[dict[str, Any]]) -> dict[str, str]:
    statuses: dict[str, str] = {}
    for item in image_stage:
        service = item.get("service")
        status = item.get("status")
        if isinstance(service, str) and isinstance(status, str):
            statuses[service] = status
    return statuses


def write_compose_image_override(
    *,
    data_root: Path,
    update_id: str,
    target_version: str,
    image_refs: list[dict[str, Any]],
    image_stage: list[dict[str, Any]],
    created_at: datetime | None = None,
) -> dict[str, Any]:
    update_id = validate_update_id(update_id)
    normalized_refs = normalize_image_refs(image_refs)
    root = data_root.resolve()
    output_dir = (root / "data" / "control-plane" / "updates" / update_id).resolve()
    if root not in output_dir.parents:
        raise ComposeOverrideError("compose override output escapes data root")
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / "compose.images.yaml"
    content = render_compose_image_override(
        update_id=update_id,
        target_version=target_version,
        image_refs=normalized_refs,
        created_at=created_at,
    )
    output_path.write_text(content, encoding="utf-8")
    output_path.chmod(0o600)
    statuses = stage_statuses(image_stage)
    not_pulled = [item["service"] for item in normalized_refs if statuses.get(item["service"]) not in PROMOTABLE_IMAGE_STAGE_STATUSES]
    return {
        "format": "b1-ai-hub-compose-image-override/v1",
        "path": str(output_path),
        "relative_path": output_path.relative_to(root).as_posix(),
        "sha256": sha256_file(output_path),
        "service_count": len(normalized_refs),
        "services": [item["service"] for item in normalized_refs],
        "ready_for_promotion": not not_pulled,
        "requires_image_pull_before_promotion": bool(not_pulled),
        "not_pulled_services": not_pulled,
        "usage": f"docker compose -f compose.yaml -f {output_path} up -d",
    }
